services:
  frontend:
    image: 'vkolesnikov88/doctr-frontend:latest'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    healthcheck:
      test: curl --fail http://localhost:80/health || exit 1
  backend:
    image: 'vkolesnikov88/doctr-backend:latest'
    ports:
      - '8085:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS}
      - SENTRY_DSN=${SENTRY_DSN}
    extra_hosts:
      - db:172.17.0.1
    healthcheck:
      test: wget -qO- http://localhost:8080/actuator/health || exit 1
