services:
  frontend:
    image: 'vkolesnikov88/doctr-frontend:2.1.0'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
  backend:
    image: 'vkolesnikov88/doctr-backend:3.0.0'
    ports:
      - '8085:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS}
      - SENTRY_DSN=${SENTRY_DSN}
    extra_hosts:
      - db:172.17.0.1
