server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false
  sql:
    init:
      mode: never

management:
  endpoint:
    health:
      show-details: when_authorized

jwt:
  token:
    secret: doctrspringboot
    expired: 999999999

logging:
  level:
    org.springframework.security: DEBUG

sentry:
  dsn: ${SENTRY_DSN}
  traces-sample-rate: 1.0
