spring:
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME}?serverTimezone=UTC
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER}
    password: ${DB_PASS}

sentry:
  dsn:
