server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://${DOCTR_DB_HOST}:5432/${DOCTR_DB_NAME}?serverTimezone=UTC
    driver-class-name: org.postgresql.Driver
    username: ${DOCTR_DB_USER}
    password: ${DOCTR_DB_PASS}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never

jwt:
  token:
    secret: doctrspringboot
    expired: 999999999

logging:
  level:
    org.springframework.security: DEBUG
