version: '2'

services:
  frontend:
    image: 'vkolesnikov88/doctr-frontend:okteto'
    container_name: frontend
    ports:
      - "8081:80"

  backend:
    image: 'vkolesnikov88/doctr-backend:2.0'
    ports:
      - "8080:8080"
    container_name: backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASS}
      - SENTRY_DSN=${SENTRY_DSN}

  db:
    image: 'postgres:13-alpine'
    ports:
      - "5432:5432"
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
