version: '2'

services:
  frontend:
    image: 'vkolesnikov88/doctr-frontend:okteto'
    container_name: frontend
    ports:
      - "8081:80"

  backend:
    image: 'vkolesnikov88/doctr-backend:1.0'
    ports:
      - "8080:8080"
    container_name: backend
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SENTRY_DSN=https://273f5579cd174cd7acef4a6cad8facbc@o1381261.ingest.sentry.io/6694950

  db:
    image: 'postgres:13-alpine'
    ports:
      - "5432:5432"
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
