TRUNCATE TABLE reminders CASCADE;
TRUNCATE TABLE patients CASCADE;
TRUNCATE TABLE clinics CASCADE;
TRUNCATE TABLE visits CASCADE;
TRUNCATE TABLE user_roles CASCADE;
TRUNCATE TABLE roles CASCADE;
TRUNCATE TABLE users CASCADE;

ALTER SEQUENCE global_seq RESTART WITH 1100;
