ALTER TABLE users
    ALTER COLUMN created SET NOT NULL,
    ALTER COLUMN updated SET NOT NULL;

ALTER TABLE roles
    ALTER COLUMN created SET NOT NULL,
    ALTER COLUMN updated SET NOT NULL;

ALTER TABLE patients
    ALTER COLUMN created SET NOT NULL,
    ALTER COLUMN updated SET NOT NULL;

ALTER TABLE clinics
    ALTER COLUMN created SET NOT NULL,
    ALTER COLUMN updated SET NOT NULL;

ALTER TABLE visits
    ALTER COLUMN created SET NOT NULL,
    ALTER COLUMN updated SET NOT NULL;

ALTER TABLE reminders
    ALTER COLUMN created SET NOT NULL,
    ALTER COLUMN updated SET NOT NULL;
